### ISSUE TITLE
a question about the algorithm

### ISSUE THREAD

**Issue by yxysday** [yatsukha/perlin-noise#1]
Hi Yatsukha,
The image generated by your algorithm is great. And I'm trying to write it in python. But I don't understand about the blending algorithm part in your statement,
in the case that max ZOOM level=32, is that means the blended value of (x,y) equal to the sum of the following expression when currentZoom changing from (31,1):
             noiseAt(x.toDouble / currentZoom, y.toDouble / currentZoom) * currentZoom / 32
Can you tell me more information about it? Thanks a lot.,

**Comment by yatsukha** [comment]
The `noiseAt` function is just pseudo-code for indexing the noise, so it refers to values of the generated noise at given coordinates.

Since we are zooming in we divide each coordinate by zoom level. So if we had a zoom level of 2 we would divide `x` and `y` by 2 to put them in a subset of the noise in the upper left corner (if we suppose the upper left corner is `(0, 0)`). 

The `currentZoom / 32` bit is wrong, as it should be just `currentZoom`, which you can see in the implementation of the `turbulence` function [here](https://github.com/yatsukha/perlin-noise/blob/13a8124c296c9e901a2fe4dd208981e7255ed02e/src/main/scala/dev/yatsukha/PerlinNoise/noise.scala#L55-L70). We are multiplying by `currentZoom` to exaggerate zoomed in parts so that they are more prevalent in the final result.

I think [this](https://lodev.org/cgtutor/randomnoise.html) is where I got the blending algorithm from. It also visualizes what multiplying by the current zoom does. I suggest you read it thoroughly.

Good luck with your python implementation :)

**Comment by yxysday** [comment]
Ok I see. Thank you very much for your explain.
